# permissions for end users to view mytasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mytask-viewer-role
rules:
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytasks/status
  verbs:
  - get
