# permissions for end users to edit mytaskruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mytaskrun-editor-role
rules:
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns/status
  verbs:
  - get
