# permissions for end users to view mytaskruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mytaskrun-viewer-role
rules:
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns/status
  verbs:
  - get
