---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns/finalizers
  verbs:
  - update
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytaskruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytasks/finalizers
  verbs:
  - update
- apiGroups:
  - cicdoperator.qi1999.io
  resources:
  - mytasks/status
  verbs:
  - get
  - patch
  - update
